"""Códigos de acción del audit log (RN-24 — catálogo cerrado)."""

from enum import StrEnum


class AuditAction(StrEnum):
    CALIFICACIONES_IMPORTAR = "CALIFICACIONES_IMPORTAR"
    PADRON_CARGAR = "PADRON_CARGAR"
    PADRON_ENTRADA_MODIFICAR = "PADRON_ENTRADA_MODIFICAR"
    COMUNICACION_ENVIAR = "COMUNICACION_ENVIAR"
    ASIGNACION_CREAR = "ASIGNACION_CREAR"
    ASIGNACION_MODIFICAR = "ASIGNACION_MODIFICAR"
    ASIGNACION_ANULAR = "ASIGNACION_ANULAR"
    LIQUIDACION_CERRAR = "LIQUIDACION_CERRAR"
    IMPERSONACION_INICIAR = "IMPERSONACION_INICIAR"
    IMPERSONACION_FINALIZAR = "IMPERSONACION_FINALIZAR"
    USUARIO_CREAR = "USUARIO_CREAR"
    USUARIO_MODIFICAR = "USUARIO_MODIFICAR"
    USUARIO_DESACTIVAR = "USUARIO_DESACTIVAR"
